title: shell-scripts
description: Standalone Bash utility scripts for a Unix dev workflow
remote_theme: just-the-docs/just-the-docs
url: https://zlatanstajic.github.io
baseurl: /shell-scripts
permalink: pretty
plugins:
  - jekyll-remote-theme
search_enabled: true
aux_links:
  GitHub: https://github.com/zlatanstajic/shell-scripts
aux_links_new_tab: true
